name: rw_tcx
description:  Dart library to either read a TCX file or write a TCX. Tested doing Strava upload. Example exporting the generated TCX to Google drive
version: 0.1.0+3
author: Patrick FINKELSTEIN <patrick@rosemarine.com>
homepage: https://github.com/BirdyF/rw_tcx


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.2.0   # To access to the sample TCX file

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

 

